name: GitHub Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day (can adjust this frequency)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate GitHub Snake
        uses: rajat12826/github-snake-action@v1.1.0
